[project]
name = "bonus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "qwen-vl-utils[decord]==0.0.8",
    "transformers>=4.53.2",
]
